/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewsRouteRouteImport } from './routes/views/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewsTodoListsIndexRouteImport } from './routes/views/todo-lists/index'
import { Route as ViewsSqlConsoleIndexRouteImport } from './routes/views/sql-console/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as ViewsTodoListsIdIndexRouteImport } from './routes/views/todo-lists/$id/index'

const ViewsRouteRoute = ViewsRouteRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsTodoListsIndexRoute = ViewsTodoListsIndexRouteImport.update({
  id: '/todo-lists/',
  path: '/todo-lists/',
  getParentRoute: () => ViewsRouteRoute,
} as any)
const ViewsSqlConsoleIndexRoute = ViewsSqlConsoleIndexRouteImport.update({
  id: '/sql-console/',
  path: '/sql-console/',
  getParentRoute: () => ViewsRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsTodoListsIdIndexRoute = ViewsTodoListsIdIndexRouteImport.update({
  id: '/todo-lists/$id/',
  path: '/todo-lists/$id/',
  getParentRoute: () => ViewsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/views': typeof ViewsRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/views/sql-console/': typeof ViewsSqlConsoleIndexRoute
  '/views/todo-lists/': typeof ViewsTodoListsIndexRoute
  '/views/todo-lists/$id/': typeof ViewsTodoListsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/views': typeof ViewsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/views/sql-console': typeof ViewsSqlConsoleIndexRoute
  '/views/todo-lists': typeof ViewsTodoListsIndexRoute
  '/views/todo-lists/$id': typeof ViewsTodoListsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/views': typeof ViewsRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/views/sql-console/': typeof ViewsSqlConsoleIndexRoute
  '/views/todo-lists/': typeof ViewsTodoListsIndexRoute
  '/views/todo-lists/$id/': typeof ViewsTodoListsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/views'
    | '/auth/login/'
    | '/auth/register/'
    | '/views/sql-console/'
    | '/views/todo-lists/'
    | '/views/todo-lists/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/views'
    | '/auth/login'
    | '/auth/register'
    | '/views/sql-console'
    | '/views/todo-lists'
    | '/views/todo-lists/$id'
  id:
    | '__root__'
    | '/'
    | '/views'
    | '/auth/login/'
    | '/auth/register/'
    | '/views/sql-console/'
    | '/views/todo-lists/'
    | '/views/todo-lists/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewsRouteRoute: typeof ViewsRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/todo-lists/': {
      id: '/views/todo-lists/'
      path: '/todo-lists'
      fullPath: '/views/todo-lists/'
      preLoaderRoute: typeof ViewsTodoListsIndexRouteImport
      parentRoute: typeof ViewsRouteRoute
    }
    '/views/sql-console/': {
      id: '/views/sql-console/'
      path: '/sql-console'
      fullPath: '/views/sql-console/'
      preLoaderRoute: typeof ViewsSqlConsoleIndexRouteImport
      parentRoute: typeof ViewsRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/todo-lists/$id/': {
      id: '/views/todo-lists/$id/'
      path: '/todo-lists/$id'
      fullPath: '/views/todo-lists/$id/'
      preLoaderRoute: typeof ViewsTodoListsIdIndexRouteImport
      parentRoute: typeof ViewsRouteRoute
    }
  }
}

interface ViewsRouteRouteChildren {
  ViewsSqlConsoleIndexRoute: typeof ViewsSqlConsoleIndexRoute
  ViewsTodoListsIndexRoute: typeof ViewsTodoListsIndexRoute
  ViewsTodoListsIdIndexRoute: typeof ViewsTodoListsIdIndexRoute
}

const ViewsRouteRouteChildren: ViewsRouteRouteChildren = {
  ViewsSqlConsoleIndexRoute: ViewsSqlConsoleIndexRoute,
  ViewsTodoListsIndexRoute: ViewsTodoListsIndexRoute,
  ViewsTodoListsIdIndexRoute: ViewsTodoListsIdIndexRoute,
}

const ViewsRouteRouteWithChildren = ViewsRouteRoute._addFileChildren(
  ViewsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewsRouteRoute: ViewsRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
